### ISSUE TITLE
Decide the product/organization name

### ISSUE THREAD

**Issue by Njima1572** [Amijakan/mochatto#1]

**Comment by siberowl** [comment]
DragVC
DragChat
DragVoice
DragSpeak
DistaVC
locusVC
RangeVC
localiaVC
proculVC
spatiumVC
DistanceVC
DynamicVC
DragTalk

**Comment by Njima1572** [comment]
BurgerChat

**Comment by Njima1572** [comment]
mochatto

**Comment by siberowl** [comment]
mochatto
もちゃっと
