### ISSUE TITLE
[Bug]: Ghost remains

### ISSUE THREAD

**Issue by Njima1572** [Amijakan/mochatto#175]
### Expected Behaviour

When a node leaves, it should leave without leaving a mess.

### Actual Behaviour

There is ghost with default color

### How to Reproduce the problem

Having two nodes in a same room. Whenever one leaves, the node becomes default color at default position.

https://user-images.githubusercontent.com/9146455/134772397-888dfcda-59d8-4190-aa87-50d7abb6737c.mp4

### Additional Info

It happened in dev mode with local server. Not sure if this will be a thing in production environment.

**Comment by siberowl** [comment]
I can't see clearly, but are the socket id's printed in the server cli for when User B joins and disconnects the same? I can't reproduce this error locally.

**Comment by siberowl** [comment]
> I can't see clearly, but are the socket id's printed in the server cli for when User B joins and disconnects the same? I can't reproduce this error locally.

The join and disconnect id's should match (8dI6Q...):
![image](https://user-images.githubusercontent.com/34047281/135356815-8e890c22-2581-4145-8a46-c1e4492a9113.png)
