### ISSUE TITLE
[Bug]: /roomname and /roomname/ should resolve to the same room

### ISSUE THREAD

**Issue by siberowl** [Amijakan/mochatto#218]
### Expected Behaviour

/roomname and /roomname/ should resolve to the same room

### Actual Behaviour

/roomname and /roomname/ are treated as separate rooms. The url should be parsed.

### How to Reproduce the problem

Go to mochatto.com/test and mochatto.com/test/

**Comment by Njima1572** [comment]
I think there are multiple approaches to it.
1. deal with it in frontend with router
2. strip the room name in server side when receiving a request with trailing slash.

I like 2nd option better.

**Comment by siberowl** [comment]
2nd option sounds good to me as well
