### ISSUE TITLE
Remove inline styling

### ISSUE THREAD

**Issue by siberowl** [Amijakan/mochatto#219]
Change to using a styling sheet.

**Comment by Njima1572** [comment]
Not sure how much of that is feasible with atomize....

**Comment by siberowl** [comment]
Yeah I agree, scss is pretty nifty imo

**Comment by siberowl** [comment]
We'd finally be able to solve #130 by moving away from Atomize as well

**Comment by Njima1572** [comment]
Well scss gets messy real quick for me as well, so open to suggestions for file organization.

**Comment by Njima1572** [comment]
I was thinking structure like this.

```
.
├── App.tsx
├── components
│   ├── Button
│   │   ├── index.tsx
│   │   └── style.scss
│   └── index.tsx
├── pages
│   ├── HomePage
│   │   ├── index.tsx
│   │   └── style.scss
│   ├── index.tsx
│   └── JoinPage
│       ├── index.tsx
│       └── style.scss
└── style.scss
```

**Comment by CaseRegan** [comment]
> I was thinking structure like this.
> 
> ```
> .
> ├── App.tsx
> ├── components
> │   ├── Button
> │   │   ├── index.tsx
> │   │   └── style.scss
> │   └── index.tsx
> ├── pages
> │   ├── HomePage
> │   │   ├── index.tsx
> │   │   └── style.scss
> │   ├── index.tsx
> │   └── JoinPage
> │       ├── index.tsx
> │       └── style.scss
> └── style.scss
> ```

I 100% agree, changed my pr to look like this
