### ISSUE TITLE
[Bug]: Favicon not found

### ISSUE THREAD

**Issue by siberowl** [Amijakan/mochatto#229]
### Expected Behaviour

Favicon should be found

### Actual Behaviour

Favicon not found

### How to Reproduce the problem

Not sure yet. Needs investigation.

### Relevant log output

![image](https://user-images.githubusercontent.com/34047281/169672845-8420c042-9298-497e-bb28-b6b104ed78ec.png)

**Comment by Njima1572** [comment]
https://github.com/Amijakan/mochatto/blob/main/logo/logo_char_light.png

We can use this file for favicon
