### ISSUE TITLE
[Refactor]: Remove unnecessary rendering

### ISSUE THREAD

**Issue by Njima1572** [Amijakan/mochatto#264]
### Refactor Request

- #260 
- #259 
This issue made me think that, the status bar should not be re-rendered when user moves.
Actually it was re rendering when other user was moving as well. That is completely unnecessary rendering.

- When avatar moves, AvatarDom should be the only component that should be rendered.
- Status Bar should not render until user changes status / mute

### Describe the proposed solution

Start introducing useMemo, useCallback, React.memo to reduce unnecessary rendering.
This will be a big chunk of refactoring, I believe, so it could be broken down into multiple stages.

### Target Components
- ButtonsBar 
  - [x] #273
- AvatarDOM
  - [x] #274

**Comment by siberowl** [comment]
Using profiling: https://reactjs.org/blog/2016/11/16/react-v15.4.0.html#profiling-components-with-chrome-timeline
I found that all the components rerender basically every frame (due to the audio visualizer).

I think this should be fixed asap.
