### ISSUE TITLE
[Refactor]: Create a shared folder between client and server

### ISSUE THREAD

**Issue by Njima1572** [Amijakan/mochatto#321]
### Refactor Request

Make types / methods in sync with frondend and backend,

### Describe the proposed solution

I was thinking of creating a folder called `shared` at the root of the project and have hard links to the files in this in both frontend and backend.

- [ ] Some of the types
- [x] SocketIO channel name enum
- [x] Authentication response code
- [ ] Hash functions (if possible)

**Comment by siberowl** [comment]
Yeah since both the backend and frontend are in js, that seems like it would work perfectly!

**Comment by Njima1572** [comment]
Git doesn't seem to preserve hard links, so I'm planning to use soft link instead.
However, tsc does not seem to like soft link, so lsp complains about the import.
