### ISSUE TITLE
[Feature]: Room authentication

### ISSUE THREAD

**Issue by siberowl** [Amijakan/mochatto#74]
### What feature?

- [ ] Generate an authentication key when creating a new room
- [ ] Add an authentication process for joining an existing room

**Comment by siberowl** [comment]
Idea: instead of managing a database, have the users hold the authentication hash themselves.
How it would work:

When user A joins a new room, they would decide on a password and keep the password hash. When user B joins the room, they would query the server which would request the hash from user A, see if B's password matches the hash, and authenticate. Once user B is authenticated, user B will now hold the hash as well.

As long as there is at least one authenticated user in the room, new comers will need to provide a password. If there's no one, a new password would be generated.

Security: If hypothetically, the stored hash is leaked by an individual, it would be useless for authentication. The only way to maliciously authenticate would be to eaves drop on the password being transferred over socketio which, would be secure with an ssl connection.

**Comment by Njima1572** [comment]
That sounds good enough to me. 
Maybe make it little nicer by adding hash(roomId + password) instead?
This would make known passwords to be less vulnerable

**Comment by siberowl** [comment]
True true sounds good

**Comment by siberowl** [comment]
Not planning to add this feature anytime soon since I don't want to add any extra steps in join page.

**Comment by siberowl** [comment]
Decided to just hold the password hash in the backend as normal since it's unnecessarily difficult to figure out who to trust when asking for the room password.
